// Sample data for demonstration with 100 entries (Thai-friendly version)
export const initialData = [
  {
    id: 1,
    datetime: "01/12/2567 08:30",
    carNo: "รถ-001",
    driver: "สมชาย มีสุข",
    group: "กลุ่ม ก",
    status: "เสร็จสิ้น",
    fieldNo: "แปลง-042",
    areaOfField: "15.5",
    owner: "บริษัท ไร่อ้อยไทย จำกัด",
    quotaGroup: "โควต้า 1",
    remark: "เสร็จก่อนกำหนด",
  },
  {
    id: 2,
    datetime: "01/12/2567 09:15",
    carNo: "รถ-002",
    driver: "วิชัย ใจดี",
    group: "กลุ่ม ข",
    status: "รอดำเนินการ",
    fieldNo: "แปลง-036",
    areaOfField: "12.8",
    owner: "หจก. อ้อยหวาน",
    quotaGroup: "โควต้า 2",
    remark: "รออุปกรณ์",
  },
  {
    id: 3,
    datetime: "01/12/2567 07:45",
    carNo: "รถ-003",
    driver: "สมศรี รักดี",
    group: "กลุ่ม ก",
    status: "กำลังรอ",
    fieldNo: "แปลง-042",
    areaOfField: "15.5",
    owner: "บริษัท ไร่อ้อยไทย จำกัด",
    quotaGroup: "โควต้า 1",
    remark: "รอการเตรียมพื้นที่",
  },
  {
    id: 4,
    datetime: "01/12/2567 10:00",
    carNo: "รถ-004",
    driver: "มานะ ตั้งใจ",
    group: "กลุ่ม ค",
    status: "ยกเลิก",
    fieldNo: "แปลง-051",
    areaOfField: "18.2",
    owner: "บริษัท ทองเพชร การเกษตร",
    quotaGroup: "โควต้า 3",
    remark: "ยกเลิกเนื่องจากสภาพอากาศ",
  },
  {
    id: 5,
    datetime: "02/12/2567 08:15",
    carNo: "รถ-005",
    driver: "สมหมาย ชอบงาน",
    group: "กลุ่ม ข",
    status: "อื่นๆ",
    fieldNo: "แปลง-038",
    areaOfField: "14.3",
    owner: "หจก. อ้อยหวาน",
    quotaGroup: "โควต้า 2",
    remark: "กำลังฝึกพนักงานใหม่",
  },
  {
    id: 6,
    datetime: "02/12/2567 11:30",
    carNo: "รถ-001",
    driver: "สมชาย มีสุข",
    group: "กลุ่ม ก",
    status: "รอดำเนินการ",
    fieldNo: "แปลง-044",
    areaOfField: "16.7",
    owner: "บริษัท ไร่อ้อยไทย จำกัด",
    quotaGroup: "โควต้า 1",
    remark: "รอการซ่อมบำรุง",
  },
  {
    id: 7,
    datetime: "03/12/2567 09:45",
    carNo: "รถ-006",
    driver: "สมบัติ มั่งมี",
    group: "กลุ่ม ค",
    status: "เสร็จสิ้น",
    fieldNo: "แปลง-039",
    areaOfField: "13.2",
    owner: "บริษัท ทุ่งเขียว จำกัด",
    quotaGroup: "โควต้า 4",
    remark: "ผลผลิตดีมาก",
  },
  {
    id: 8,
    datetime: "03/12/2567 10:20",
    carNo: "รถ-007",
    driver: "สมพร รักงาน",
    group: "กลุ่ม ก",
    status: "กำลังรอ",
    fieldNo: "แปลง-045",
    areaOfField: "17.8",
    owner: "บริษัท ไร่อ้อยไทย จำกัด",
    quotaGroup: "โควต้า 1",
    remark: "รอรถขนส่ง",
  },
  {
    id: 9,
    datetime: "04/12/2567 08:40",
    carNo: "รถ-003",
    driver: "สมศรี รักดี",
    group: "กลุ่ม ก",
    status: "เสร็จสิ้น",
    fieldNo: "แปลง-042",
    areaOfField: "15.5",
    owner: "บริษัท ไร่อ้อยไทย จำกัด",
    quotaGroup: "โควต้า 1",
    remark: "ตัดเสร็จในโซน A",
  },
  {
    id: 10,
    datetime: "04/12/2567 12:00",
    carNo: "รถ-008",
    driver: "สมใจ ใจเย็น",
    group: "กลุ่ม ข",
    status: "ยกเลิก",
    fieldNo: "แปลง-047",
    areaOfField: "11.9",
    owner: "หจก. อ้อยหวาน",
    quotaGroup: "โควต้า 2",
    remark: "ปัญหาเครื่องจักร ต้องตรวจสอบ",
  },
  {
    id: 11,
    datetime: "05/12/2567 07:30",
    carNo: "รถ-009",
    driver: "ประเสริฐ ศรีสกุล",
    group: "กลุ่ม ค",
    status: "เสร็จสิ้น",
    fieldNo: "แปลง-052",
    areaOfField: "16.3",
    owner: "บริษัท ทองเพชร การเกษตร",
    quotaGroup: "โควต้า 3",
    remark: "คุณภาพผลผลิตดีเยี่ยม",
  },
  {
    id: 12,
    datetime: "05/12/2567 09:15",
    carNo: "รถ-010",
    driver: "วิไล สุขใจ",
    group: "กลุ่ม ข",
    status: "กำลังรอ",
    fieldNo: "แปลง-039",
    areaOfField: "13.2",
    owner: "บริษัท ทุ่งเขียว จำกัด",
    quotaGroup: "โควต้า 4",
    remark: "รอการชลประทานพื้นที่",
  },
  {
    id: 13,
    datetime: "06/12/2567 08:00",
    carNo: "รถ-002",
    driver: "วิชัย ใจดี",
    group: "กลุ่ม ข",
    status: "เสร็จสิ้น",
    fieldNo: "แปลง-036",
    areaOfField: "12.8",
    owner: "หจก. อ้อยหวาน",
    quotaGroup: "โควต้า 2",
    remark: "ผลผลิตดี ทำงานเสร็จสิ้น",
  },
  {
    id: 14,
    datetime: "06/12/2567 10:30",
    carNo: "รถ-011",
    driver: "สมบูรณ์ ทรัพย์มาก",
    group: "กลุ่ม ก",
    status: "รอดำเนินการ",
    fieldNo: "แปลง-046",
    areaOfField: "14.6",
    owner: "บริษัท ไร่อ้อยไทย จำกัด",
    quotaGroup: "โควต้า 1",
    remark: "กำหนดดำเนินการช่วงบ่าย",
  },
  {
    id: 15,
    datetime: "07/12/2567 07:45",
    carNo: "รถ-004",
    driver: "มานะ ตั้งใจ",
    group: "กลุ่ม ค",
    status: "อื่นๆ",
    fieldNo: "แปลง-053",
    areaOfField: "17.1",
    owner: "บริษัท ทองเพชร การเกษตร",
    quotaGroup: "โควต้า 3",
    remark: "กำลังปรับแต่งอุปกรณ์",
  },
  {
    id: 16,
    datetime: "07/12/2567 09:30",
    carNo: "รถ-012",
    driver: "สุรชัย คงเกษม",
    group: "กลุ่ม ค",
    status: "เสร็จสิ้น",
    fieldNo: "แปลง-054",
    areaOfField: "19.5",
    owner: "บริษัท ทองเพชร การเกษตร",
    quotaGroup: "โควต้า 3",
    remark: "ตัดพื้นที่ใหญ่เสร็จอย่างมีประสิทธิภาพ",
  },
  {
    id: 17,
    datetime: "08/12/2567 08:15",
    carNo: "รถ-007",
    driver: "สมพร รักงาน",
    group: "กลุ่ม ก",
    status: "เสร็จสิ้น",
    fieldNo: "แปลง-045",
    areaOfField: "17.8",
    owner: "บริษัท ไร่อ้อยไทย จำกัด",
    quotaGroup: "โควต้า 1",
    remark: "การดำเนินงานเสร็จสิ้นด้วยดี",
  },
  {
    id: 18,
    datetime: "08/12/2567 11:00",
    carNo: "รถ-013",
    driver: "รัตนา ศิลปดี",
    group: "กลุ่ม ข",
    status: "ยกเลิก",
    fieldNo: "แปลง-048",
    areaOfField: "12.4",
    owner: "หจก. อ้อยหวาน",
    quotaGroup: "โควต้า 2",
    remark: "ยกเลิกเนื่องจากปัญหาเครื่องจักร",
  },
  {
    id: 19,
    datetime: "09/12/2567 07:30",
    carNo: "รถ-005",
    driver: "สมหมาย ชอบงาน",
    group: "กลุ่ม ข",
    status: "กำลังรอ",
    fieldNo: "แปลง-041",
    areaOfField: "15.8",
    owner: "หจก. อ้อยหวาน",
    quotaGroup: "โควต้า 2",
    remark: "รอการอนุมัติเข้าพื้นที่",
  },
  {
    id: 20,
    datetime: "09/12/2567 09:45",
    carNo: "รถ-014",
    driver: "ไพศาล โชคดี",
    group: "กลุ่ม ก",
    status: "รอดำเนินการ",
    fieldNo: "แปลง-049",
    areaOfField: "16.2",
    owner: "บริษัท ไร่อ้อยไทย จำกัด",
    quotaGroup: "โควต้า 1",
    remark: "กำหนดการช่วงบ่ายแก่",
  },
  {
    id: 21,
    datetime: "10/12/2567 08:00",
    carNo: "รถ-015",
    driver: "พรทิพย์ สุขสวัสดิ์",
    group: "กลุ่ม ค",
    status: "เสร็จสิ้น",
    fieldNo: "แปลง-055",
    areaOfField: "14.9",
    owner: "บริษัท ทุ่งเขียว จำกัด",
    quotaGroup: "โควต้า 4",
    remark: "เสร็จก่อนเวลาที่กำหนด",
  },
  {
    id: 22,
    datetime: "10/12/2567 10:30",
    carNo: "รถ-016",
    driver: "วันชัย สุขสันต์",
    group: "กลุ่ม ก",
    status: "ยกเลิก",
    fieldNo: "แปลง-056",
    areaOfField: "18.7",
    owner: "บริษัท ไร่อ้อยไทย จำกัด",
    quotaGroup: "โควต้า 1",
    remark: "ยกเลิกเนื่องจากพื้นที่ไม่พร้อม",
  },
  {
    id: 23,
    datetime: "11/12/2567 07:45",
    carNo: "รถ-008",
    driver: "สมใจ ใจเย็น",
    group: "กลุ่ม ข",
    status: "กำลังรอ",
    fieldNo: "แปลง-057",
    areaOfField: "13.6",
    owner: "หจก. อ้อยหวาน",
    quotaGroup: "โควต้า 2",
    remark: "รอการเตรียมพื้นที่เสร็จสิ้น",
  },
  {
    id: 24,
    datetime: "11/12/2567 09:30",
    carNo: "รถ-017",
    driver: "ประภาส จิตรดี",
    group: "กลุ่ม ค",
    status: "อื่นๆ",
    fieldNo: "แปลง-058",
    areaOfField: "16.4",
    owner: "บริษัท ทองเพชร การเกษตร",
    quotaGroup: "โควต้า 3",
    remark: "ทดสอบเทคนิคการตัดใหม่",
  },
  {
    id: 25,
    datetime: "12/12/2567 08:15",
    carNo: "รถ-001",
    driver: "สมชาย มีสุข",
    group: "กลุ่ม ก",
    status: "เสร็จสิ้น",
    fieldNo: "แปลง-059",
    areaOfField: "15.1",
    owner: "บริษัท ไร่อ้อยไทย จำกัด",
    quotaGroup: "โควต้า 1",
    remark: "ตัดอ้อยช่วงเช้าเสร็จสมบูรณ์",
  },
  {
    id: 26,
    datetime: "12/12/2567 10:00",
    carNo: "รถ-018",
    driver: "อมรา ชาญชัย",
    group: "กลุ่ม ค",
    status: "รอดำเนินการ",
    fieldNo: "แปลง-060",
    areaOfField: "16.8",
    owner: "บริษัท ทุ่งเขียว จำกัด",
    quotaGroup: "โควต้า 4",
    remark: "กำหนดงานช่วงเช้าตรู่",
  },
  {
    id: 27,
    datetime: "13/12/2567 07:30",
    carNo: "รถ-019",
    driver: "การุณ มีเมตตา",
    group: "กลุ่ม ข",
    status: "เสร็จสิ้น",
    fieldNo: "แปลง-061",
    areaOfField: "14.5",
    owner: "หจก. อ้อยหวาน",
    quotaGroup: "โควต้า 2",
    remark: "ตัดเสร็จด้วยประสิทธิภาพสูง",
  },
  {
    id: 28,
    datetime: "13/12/2567 09:15",
    carNo: "รถ-020",
    driver: "สุภาพร นิ่มนวล",
    group: "กลุ่ม ก",
    status: "กำลังรอ",
    fieldNo: "แปลง-062",
    areaOfField: "17.3",
    owner: "บริษัท ไร่อ้อยไทย จำกัด",
    quotaGroup: "โควต้า 1",
    remark: "รอการทำเครื่องหมายแปลง",
  },
  {
    id: 29,
    datetime: "14/12/2567 08:00",
    carNo: "รถ-007",
    driver: "สมพร รักงาน",
    group: "กลุ่ม ก",
    status: "เสร็จสิ้น",
    fieldNo: "แปลง-063",
    areaOfField: "15.9",
    owner: "บริษัท ไร่อ้อยไทย จำกัด",
    quotaGroup: "โควต้า 1",
    remark: "ตัดแปลงเสร็จด้วยผลผลิตสูง",
  },
  {
    id: 30,
    datetime: "14/12/2567 10:30",
    carNo: "รถ-021",
    driver: "นิรันดร์ สุขเสมอ",
    group: "กลุ่ม ข",
    status: "ยกเลิก",
    fieldNo: "แปลง-064",
    areaOfField: "13.7",
    owner: "หจก. อ้อยหวาน",
    quotaGroup: "โควต้า 2",
    remark: "ยกเลิกเนื่องจากเครื่องจักรร้อนเกิน",
  },
  {
    id: 31,
    datetime: "15/12/2567 07:45",
    carNo: "รถ-006",
    driver: "สมบัติ มั่งมี",
    group: "กลุ่ม ค",
    status: "อื่นๆ",
    fieldNo: "แปลง-065",
    areaOfField: "18.4",
    owner: "บริษัท ทองเพชร การเกษตร",
    quotaGroup: "โควต้า 3",
    remark: "ทดสอบรูปแบบการตัดพิเศษ",
  },
  {
    id: 32,
    datetime: "15/12/2567 09:30",
    carNo: "รถ-022",
    driver: "ประสิทธิ์ งานดี",
    group: "กลุ่ม ก",
    status: "รอดำเนินการ",
    fieldNo: "แปลง-066",
    areaOfField: "16.5",
    owner: "บริษัท ไร่อ้อยไทย จำกัด",
    quotaGroup: "โควต้า 1",
    remark: "รอการจัดสรรทีมงาน",
  },
  {
    id: 33,
    datetime: "16/12/2567 08:15",
    carNo: "รถ-004",
    driver: "มานะ ตั้งใจ",
    group: "กลุ่ม ค",
    status: "เสร็จสิ้น",
    fieldNo: "แปลง-067",
    areaOfField: "15.3",
    owner: "บริษัท ทองเพชร การเกษตร",
    quotaGroup: "โควต้า 3",
    remark: "ตัดเสร็จหลังการปรับแต่งอุปกรณ์",
  },
  {
    id: 34,
    datetime: "16/12/2567 10:00",
    carNo: "รถ-023",
    driver: "ลิขิต มากเพชร",
    group: "กลุ่ม ข",
    status: "กำลังรอ",
    fieldNo: "แปลง-068",
    areaOfField: "14.7",
    owner: "หจก. อ้อยหวาน",
    quotaGroup: "โควต้า 2",
    remark: "รอการระบายน้ำในพื้นที่",
  },
  {
    id: 35,
    datetime: "17/12/2567 07:30",
    carNo: "รถ-009",
    driver: "ประเสริฐ ศรีสกุล",
    group: "กลุ่ม ค",
    status: "เสร็จสิ้น",
    fieldNo: "แปลง-069",
    areaOfField: "17.6",
    owner: "บริษัท ทองเพชร การเกษตร",
    quotaGroup: "โควต้า 3",
    remark: "ตัดอ้อยตอนเช้าเสร็จสมบูรณ์",
  },
  {
    id: 36,
    datetime: "17/12/2567 09:15",
    carNo: "รถ-024",
    driver: "อิสรา สู้งาน",
    group: "กลุ่ม ก",
    status: "อื่นๆ",
    fieldNo: "แปลง-070",
    areaOfField: "15.8",
    owner: "บริษัท ไร่อ้อยไทย จำกัด",
    quotaGroup: "โควต้า 1",
    remark: "ทดสอบวิธีการตัดใหม่",
  },
  {
    id: 37,
    datetime: "18/12/2567 08:00",
    carNo: "รถ-002",
    driver: "วิชัย ใจดี",
    group: "กลุ่ม ข",
    status: "รอดำเนินการ",
    fieldNo: "แปลง-071",
    areaOfField: "13.9",
    owner: "หจก. อ้อยหวาน",
    quotaGroup: "โควต้า 2",
    remark: "งานวันถัดไปหลังซ่อมบำรุง",
  },
  {
    id: 38,
    datetime: "18/12/2567 10:30",
    carNo: "รถ-025",
    driver: "ณรงค์ศักดิ์ งามแสง",
    group: "กลุ่ม ค",
    status: "เสร็จสิ้น",
    fieldNo: "แปลง-072",
    areaOfField: "16.9",
    owner: "บริษัท ทองเพชร การเกษตร",
    quotaGroup: "โควต้า 3",
    remark: "ตัดเสร็จด้วยผลผลิตสูง",
  },
  {
    id: 39,
    datetime: "19/12/2567 07:45",
    carNo: "รถ-003",
    driver: "สมศรี รักดี",
    group: "กลุ่ม ก",
    status: "ยกเลิก",
    fieldNo: "แปลง-073",
    areaOfField: "15.4",
    owner: "บริษัท ไร่อ้อยไทย จำกัด",
    quotaGroup: "โควต้า 1",
    remark: "ยกเลิกเนื่องจากความปลอดภัย",
  },
  {
    id: 40,
    datetime: "19/12/2567 09:30",
    carNo: "รถ-026",
    driver: "มิ่งขวัญ ชูศรี",
    group: "กลุ่ม ข",
    status: "กำลังรอ",
    fieldNo: "แปลง-074",
    areaOfField: "14.8",
    owner: "หจก. อ้อยหวาน",
    quotaGroup: "โควต้า 2",
    remark: "รอการหมุนเวียนทีมงาน",
  },
  {
    id: 41,
    datetime: "20/12/2567 08:15",
    carNo: "รถ-005",
    driver: "สมหมาย ชอบงาน",
    group: "กลุ่ม ข",
    status: "เสร็จสิ้น",
    fieldNo: "แปลง-075",
    areaOfField: "17.2",
    owner: "หจก. อ้อยหวาน",
    quotaGroup: "โควต้า 2",
    remark: "ตัดเสร็จด้วยประสิทธิภาพดี",
  },
  {
    id: 42,
    datetime: "20/12/2567 10:00",
    carNo: "รถ-027",
    driver: "ปรีชา คนสู้",
    group: "กลุ่ม ก",
    status: "อื่นๆ",
    fieldNo: "แปลง-076",
    areaOfField: "16.1",
    owner: "บริษัท ไร่อ้อยไทย จำกัด",
    quotaGroup: "โควต้า 1",
    remark: "สาธิตอุปกรณ์ให้พนักงานใหม่",
  },
  {
    id: 43,
    datetime: "21/12/2567 07:30",
    carNo: "รถ-012",
    driver: "สุรชัย คงเกษม",
    group: "กลุ่ม ค",
    status: "รอดำเนินการ",
    fieldNo: "แปลง-077",
    areaOfField: "18.3",
    owner: "บริษัท ทองเพชร การเกษตร",
    quotaGroup: "โควต้า 3",
    remark: "กำหนดการตัดอ้อยช่วงเช้าตรู่",
  },
  {
    id: 44,
    datetime: "21/12/2567 09:15",
    carNo: "รถ-028",
    driver: "วารี สดใส",
    group: "กลุ่ม ข",
    status: "เสร็จสิ้น",
    fieldNo: "แปลง-078",
    areaOfField: "15.7",
    owner: "หจก. อ้อยหวาน",
    quotaGroup: "โควต้า 2",
    remark: "งานแรกเสร็จสมบูรณ์",
  },
  {
    id: 45,
    datetime: "22/12/2567 08:00",
    carNo: "รถ-008",
    driver: "สมใจ ใจเย็น",
    group: "กลุ่ม ข",
    status: "กำลังรอ",
    fieldNo: "แปลง-079",
    areaOfField: "13.4",
    owner: "หจก. อ้อยหวาน",
    quotaGroup: "โควต้า 2",
    remark: "รอการเคลียร์พื้นที่",
  },
  {
    id: 46,
    datetime: "22/12/2567 10:30",
    carNo: "รถ-029",
    driver: "ภาณุ มากแสง",
    group: "กลุ่ม ก",
    status: "ยกเลิก",
    fieldNo: "แปลง-080",
    areaOfField: "17.9",
    owner: "บริษัท ไร่อ้อยไทย จำกัด",
    quotaGroup: "โควต้า 1",
    remark: "ยกเลิกเนื่องจากสภาพพื้นที่ไม่เอื้ออำนวย",
  },
  {
    id: 47,
    datetime: "23/12/2567 07:45",
    carNo: "รถ-014",
    driver: "ไพศาล โชคดี",
    group: "กลุ่ม ก",
    status: "เสร็จสิ้น",
    fieldNo: "แปลง-081",
    areaOfField: "16.6",
    owner: "บริษัท ไร่อ้อยไทย จำกัด",
    quotaGroup: "โควต้า 1",
    remark: "ตัดได้คุณภาพดีเยี่ยม",
  },
  {
    id: 48,
    datetime: "23/12/2567 09:30",
    carNo: "รถ-030",
    driver: "ปรียา ใจรัก",
    group: "กลุ่ม ค",
    status: "อื่นๆ",
    fieldNo: "แปลง-082",
    areaOfField: "15.2",
    owner: "บริษัท ทุ่งเขียว จำกัด",
    quotaGroup: "โควต้า 4",
    remark: "กำลังประเมินประสิทธิภาพอุปกรณ์",
  },
  {
    id: 49,
    datetime: "24/12/2567 08:15",
    carNo: "รถ-001",
    driver: "สมชาย มีสุข",
    group: "กลุ่ม ก",
    status: "รอดำเนินการ",
    fieldNo: "แปลง-083",
    areaOfField: "14.2",
    owner: "บริษัท ไร่อ้อยไทย จำกัด",
    quotaGroup: "โควต้า 1",
    remark: "รอการเตรียมพื้นที่เสร็จสิ้น",
  },
  {
    id: 50,
    datetime: "24/12/2567 10:00",
    carNo: "รถ-010",
    driver: "วิไล สุขใจ",
    group: "กลุ่ม ข",
    status: "เสร็จสิ้น",
    fieldNo: "แปลง-084",
    areaOfField: "18.5",
    owner: "บริษัท ทุ่งเขียว จำกัด",
    quotaGroup: "โควต้า 4",
    remark: "ตัดพื้นที่ใหญ่เสร็จอย่างมีประสิทธิภาพ",
  },
  {
    id: 51,
    datetime: "25/12/2567 07:30",
    carNo: "รถ-031",
    driver: "สมพงษ์ ไพศาล",
    group: "กลุ่ม ก",
    status: "เสร็จสิ้น",
    fieldNo: "แปลง-085",
    areaOfField: "16.3",
    owner: "บริษัท ไร่อ้อยไทย จำกัด",
    quotaGroup: "โควต้า 1",
    remark: "ตัดอ้อยครั้งแรกของเดือนเสร็จสิ้น",
  },
  {
    id: 52,
    datetime: "25/12/2567 09:15",
    carNo: "รถ-032",
    driver: "สุธี ชัยภักดี",
    group: "กลุ่ม ข",
    status: "รอดำเนินการ",
    fieldNo: "แปลง-086",
    areaOfField: "14.7",
    owner: "หจก. อ้อยหวาน",
    quotaGroup: "โควต้า 2",
    remark: "ตรวจเช็คสภาพเครื่องจักรก่อนใช้งาน",
  },
  {
    id: 53,
    datetime: "26/12/2567 08:00",
    carNo: "รถ-033",
    driver: "อรอุมา สุขศรี",
    group: "กลุ่ม ค",
    status: "กำลังรอ",
    fieldNo: "แปลง-087",
    areaOfField: "15.8",
    owner: "บริษัท ทองเพชร การเกษตร",
    quotaGroup: "โควต้า 3",
    remark: "รอการประเมินสภาพพื้นที่",
  },
  {
    id: 54,
    datetime: "26/12/2567 10:30",
    carNo: "รถ-034",
    driver: "วิทยา ศรีเมือง",
    group: "กลุ่ม ก",
    status: "ยกเลิก",
    fieldNo: "แปลง-088",
    areaOfField: "17.5",
    owner: "บริษัท ไร่อ้อยไทย จำกัด",
    quotaGroup: "โควต้า 1",
    remark: "ยกเลิกเนื่องจากเครื่องจักรขัดข้อง",
  },
  {
    id: 55,
    datetime: "27/12/2567 07:45",
    carNo: "รถ-035",
    driver: "วิภา ศรีสวัสดิ์",
    group: "กลุ่ม ข",
    status: "อื่นๆ",
    fieldNo: "แปลง-089",
    areaOfField: "13.9",
    owner: "หจก. อ้อยหวาน",
    quotaGroup: "โควต้า 2",
    remark: "อบรมพนักงานใหม่",
  },
  {
    id: 56,
    datetime: "27/12/2567 09:30",
    carNo: "รถ-018",
    driver: "อมรา ชาญชัย",
    group: "กลุ่ม ค",
    status: "เสร็จสิ้น",
    fieldNo: "แปลง-090",
    areaOfField: "16.1",
    owner: "บริษัท ทุ่งเขียว จำกัด",
    quotaGroup: "โควต้า 4",
    remark: "เสร็จก่อนกำหนด",
  },
  {
    id: 57,
    datetime: "28/12/2567 08:15",
    carNo: "รถ-036",
    driver: "ประวิทย์ รักถิ่น",
    group: "กลุ่ม ก",
    status: "รอดำเนินการ",
    fieldNo: "แปลง-091",
    areaOfField: "18.2",
    owner: "บริษัท ไร่อ้อยไทย จำกัด",
    quotaGroup: "โควต้า 1",
    remark: "กำหนดการช่วงบ่าย",
  },
  {
    id: 58,
    datetime: "28/12/2567 10:00",
    carNo: "รถ-037",
    driver: "พิมพ์ใจ รักษ์ดี",
    group: "กลุ่ม ข",
    status: "กำลังรอ",
    fieldNo: "แปลง-092",
    areaOfField: "15.3",
    owner: "หจก. อ้อยหวาน",
    quotaGroup: "โควต้า 2",
    remark: "รอการจัดการโลจิสติกส์",
  },
  {
    id: 59,
    datetime: "29/12/2567 07:30",
    carNo: "รถ-019",
    driver: "การุณ มีเมตตา",
    group: "กลุ่ม ข",
    status: "เสร็จสิ้น",
    fieldNo: "แปลง-093",
    areaOfField: "14.5",
    owner: "หจก. อ้อยหวาน",
    quotaGroup: "โควต้า 2",
    remark: "ตัดเสร็จในพื้นที่ส่วน B",
  },
  {
    id: 60,
    datetime: "29/12/2567 09:15",
    carNo: "รถ-038",
    driver: "ธีรพงษ์ วิจิตร",
    group: "กลุ่ม ค",
    status: "ยกเลิก",
    fieldNo: "แปลง-094",
    areaOfField: "16.8",
    owner: "บริษัท ทองเพชร การเกษตร",
    quotaGroup: "โควต้า 3",
    remark: "สภาพอากาศไม่เอื้ออำนวย",
  },
  {
    id: 61,
    datetime: "30/12/2567 08:00",
    carNo: "รถ-013",
    driver: "รัตนา ศิลปดี",
    group: "กลุ่ม ข",
    status: "อื่นๆ",
    fieldNo: "แปลง-095",
    areaOfField: "13.7",
    owner: "หจก. อ้อยหวาน",
    quotaGroup: "โควต้า 2",
    remark: "ทดสอบเทคนิคการตัดใหม่",
  },
  {
    id: 62,
    datetime: "30/12/2567 10:30",
    carNo: "รถ-039",
    driver: "อำนาจ ชัยพร",
    group: "กลุ่ม ก",
    status: "เสร็จสิ้น",
    fieldNo: "แปลง-096",
    areaOfField: "17.3",
    owner: "บริษัท ไร่อ้อยไทย จำกัด",
    quotaGroup: "โควต้า 1",
    remark: "ตัดแปลงได้ประสิทธิภาพสูง",
  },
  {
    id: 63,
    datetime: "31/12/2567 07:45",
    carNo: "รถ-040",
    driver: "ชัญญา สุขมาก",
    group: "กลุ่ม ข",
    status: "รอดำเนินการ",
    fieldNo: "แปลง-097",
    areaOfField: "15.6",
    owner: "หจก. อ้อยหวาน",
    quotaGroup: "โควต้า 2",
    remark: "รอการซ่อมบำรุงเสร็จสิ้น",
  },
  {
    id: 64,
    datetime: "31/12/2567 09:30",
    carNo: "รถ-041",
    driver: "นรินทร์ ศรีสมบัติ",
    group: "กลุ่ม ค",
    status: "กำลังรอ",
    fieldNo: "แปลง-098",
    areaOfField: "16.2",
    owner: "บริษัท ทองเพชร การเกษตร",
    quotaGroup: "โควต้า 3",
    remark: "รอการชลประทานในพื้นที่เสร็จสิ้น",
  },
  {
    id: 65,
    datetime: "01/12/2567 10:15",
    carNo: "รถ-023",
    driver: "ลิขิต มากเพชร",
    group: "กลุ่ม ข",
    status: "เสร็จสิ้น",
    fieldNo: "แปลง-099",
    areaOfField: "14.8",
    owner: "หจก. อ้อยหวาน",
    quotaGroup: "โควต้า 2",
    remark: "ตัดเสร็จก่อนเวลาเป้าหมาย",
  },
  {
    id: 66,
    datetime: "01/12/2567 11:30",
    carNo: "รถ-042",
    driver: "อัญชลี สุขเกษม",
    group: "กลุ่ม ก",
    status: "ยกเลิก",
    fieldNo: "แปลง-100",
    areaOfField: "18.1",
    owner: "บริษัท ไร่อ้อยไทย จำกัด",
    quotaGroup: "โควต้า 1",
    remark: "เครื่องจักรขัดข้องทางกล",
  },
  {
    id: 67,
    datetime: "02/12/2567 08:30",
    carNo: "รถ-043",
    driver: "สมศักดิ์ ปิ่นทอง",
    group: "กลุ่ม ข",
    status: "อื่นๆ",
    fieldNo: "แปลง-101",
    areaOfField: "15.4",
    owner: "หจก. อ้อยหวาน",
    quotaGroup: "โควต้า 2",
    remark: "ติดตั้งอุปกรณ์เสริม",
  },
  {
    id: 68,
    datetime: "02/12/2567 10:00",
    carNo: "รถ-026",
    driver: "มิ่งขวัญ ชูศรี",
    group: "กลุ่ม ข",
    status: "เสร็จสิ้น",
    fieldNo: "แปลง-102",
    areaOfField: "14.6",
    owner: "หจก. อ้อยหวาน",
    quotaGroup: "โควต้า 2",
    remark: "ผลผลิตคุณภาพดีเยี่ยม",
  },
  {
    id: 69,
    datetime: "03/12/2567 09:00",
    carNo: "รถ-044",
    driver: "กิตติพงษ์ ใจกล้า",
    group: "กลุ่ม ค",
    status: "รอดำเนินการ",
    fieldNo: "แปลง-103",
    areaOfField: "16.5",
    owner: "บริษัท ทองเพชร การเกษตร",
    quotaGroup: "โควต้า 3",
    remark: "กำหนดช่วงสายของวัน",
  },
  {
    id: 70,
    datetime: "03/12/2567 11:15",
    carNo: "รถ-045",
    driver: "พรนภา คงดี",
    group: "กลุ่ม ก",
    status: "กำลังรอ",
    fieldNo: "แปลง-104",
    areaOfField: "17.7",
    owner: "บริษัท ไร่อ้อยไทย จำกัด",
    quotaGroup: "โควต้า 1",
    remark: "รอการเคลียร์เส้นทางเข้าพื้นที่",
  },
  {
    id: 71,
    datetime: "04/12/2567 08:45",
    carNo: "รถ-025",
    driver: "ณรงค์ศักดิ์ งามแสง",
    group: "กลุ่ม ค",
    status: "เสร็จสิ้น",
    fieldNo: "แปลง-105",
    areaOfField: "16.9",
    owner: "บริษัท ทองเพชร การเกษตร",
    quotaGroup: "โควต้า 3",
    remark: "ตัดแปลงเสร็จมีประสิทธิภาพ",
  },
  {
    id: 72,
    datetime: "04/12/2567 10:30",
    carNo: "รถ-046",
    driver: "จารุวรรณ ศรีสมุทร",
    group: "กลุ่ม ข",
    status: "ยกเลิก",
    fieldNo: "แปลง-106",
    areaOfField: "14.3",
    owner: "หจก. อ้อยหวาน",
    quotaGroup: "โควต้า 2",
    remark: "ยกเลิกเนื่องจากฝนตกหนัก",
  },
  {
    id: 73,
    datetime: "05/12/2567 09:15",
    carNo: "รถ-029",
    driver: "ภาณุ มากแสง",
    group: "กลุ่ม ก",
    status: "อื่นๆ",
    fieldNo: "แปลง-107",
    areaOfField: "17.5",
    owner: "บริษัท ไร่อ้อยไทย จำกัด",
    quotaGroup: "โควต้า 1",
    remark: "ทดสอบประสิทธิภาพการใช้เชื้อเพลิง",
  },
  {
    id: 74,
    datetime: "05/12/2567 11:00",
    carNo: "รถ-047",
    driver: "ธงชัย นครไทย",
    group: "กลุ่ม ค",
    status: "เสร็จสิ้น",
    fieldNo: "แปลง-108",
    areaOfField: "15.8",
    owner: "บริษัท ทองเพชร การเกษตร",
    quotaGroup: "โควต้า 3",
    remark: "ตัดเสร็จตามกำหนดเวลา",
  },
  {
    id: 75,
    datetime: "06/12/2567 08:30",
    carNo: "รถ-048",
    driver: "จิตรา รักษ์สุข",
    group: "กลุ่ม ก",
    status: "รอดำเนินการ",
    fieldNo: "แปลง-109",
    areaOfField: "16.4",
    owner: "บริษัท ไร่อ้อยไทย จำกัด",
    quotaGroup: "โควต้า 1",
    remark: "จัดสรรพนักงานสำหรับวันหยุด",
  },
  {
    id: 76,
    datetime: "06/12/2567 10:15",
    carNo: "รถ-031",
    driver: "สมพงษ์ ไพศาล",
    group: "กลุ่ม ก",
    status: "กำลังรอ",
    fieldNo: "แปลง-110",
    areaOfField: "16.3",
    owner: "บริษัท ไร่อ้อยไทย จำกัด",
    quotaGroup: "โควต้า 1",
    remark: "รอการตรวจสอบพื้นที่",
  },
  {
    id: 77,
    datetime: "07/12/2567 09:00",
    carNo: "รถ-049",
    driver: "สุวิทย์ ชมพู",
    group: "กลุ่ม ข",
    status: "เสร็จสิ้น",
    fieldNo: "แปลง-111",
    areaOfField: "14.9",
    owner: "หจก. อ้อยหวาน",
    quotaGroup: "โควต้า 2",
    remark: "ตัดเสร็จได้ผลผลิตดี",
  },
  {
    id: 78,
    datetime: "07/12/2567 11:30",
    carNo: "รถ-050",
    driver: "ศิริลักษณ์ นภดล",
    group: "กลุ่ม ค",
    status: "ยกเลิก",
    fieldNo: "แปลง-112",
    areaOfField: "17.1",
    owner: "บริษัท ทองเพชร การเกษตร",
    quotaGroup: "โควต้า 3",
    remark: "ยกเลิกเนื่องจากปัญหาเครื่องจักร",
  },
  {
    id: 79,
    datetime: "08/12/2567 08:45",
    carNo: "รถ-034",
    driver: "วิทยา ศรีเมือง",
    group: "กลุ่ม ก",
    status: "อื่นๆ",
    fieldNo: "แปลง-113",
    areaOfField: "17.8",
    owner: "บริษัท ไร่อ้อยไทย จำกัด",
    quotaGroup: "โควต้า 1",
    remark: "ตรวจสอบเครื่องจักรประจำปี",
  },
  {
    id: 80,
    datetime: "08/12/2567 10:30",
    carNo: "รถ-051",
    driver: "รุ่งเพชร วงศ์ไทย",
    group: "กลุ่ม ข",
    status: "เสร็จสิ้น",
    fieldNo: "แปลง-114",
    areaOfField: "15.2",
    owner: "หจก. อ้อยหวาน",
    quotaGroup: "โควต้า 2",
    remark: "ตัดแปลงเสร็จเพื่อรายงานสิ้นปี",
  },
  {
    id: 81,
    datetime: "09/12/2567 09:15",
    carNo: "รถ-052",
    driver: "พิชัย ประสิทธิ์",
    group: "กลุ่ม ค",
    status: "รอดำเนินการ",
    fieldNo: "แปลง-115",
    areaOfField: "16.7",
    owner: "บริษัท ทองเพชร การเกษตร",
    quotaGroup: "โควต้า 3",
    remark: "งานสุดท้ายของปี",
  },
  {
    id: 82,
    datetime: "09/12/2567 11:00",
    carNo: "รถ-037",
    driver: "พิมพ์ใจ รักษ์ดี",
    group: "กลุ่ม ข",
    status: "กำลังรอ",
    fieldNo: "แปลง-116",
    areaOfField: "15.3",
    owner: "หจก. อ้อยหวาน",
    quotaGroup: "โควต้า 2",
    remark: "รอการทำเครื่องหมายแนวเขต",
  },
  {
    id: 83,
    datetime: "10/12/2567 08:30",
    carNo: "รถ-053",
    driver: "ภูมิพันธ์ คุณธรรม",
    group: "กลุ่ม ก",
    status: "เสร็จสิ้น",
    fieldNo: "แปลง-117",
    areaOfField: "17.4",
    owner: "บริษัท ไร่อ้อยไทย จำกัด",
    quotaGroup: "โควต้า 1",
    remark: "ตัดช่วงบ่ายเสร็จสมบูรณ์",
  },
  {
    id: 84,
    datetime: "10/12/2567 10:15",
    carNo: "รถ-054",
    driver: "ชนิดา บุษราคัม",
    group: "กลุ่ม ค",
    status: "ยกเลิก",
    fieldNo: "แปลง-118",
    areaOfField: "16.2",
    owner: "บริษัท ทองเพชร การเกษตร",
    quotaGroup: "โควต้า 3",
    remark: "ยกเลิกเนื่องจากทัศนวิสัยไม่ดี",
  },
];

// Add Thai status mapping for filtering
export const statusMapping = {
  เสร็จสิ้น: "Done",
  รอดำเนินการ: "Pending",
  กำลังรอ: "Waiting",
  ยกเลิก: "Cancel",
  อื่นๆ: "Other",
};

// Function to get English status for color coding
export const getStatusColor = (thaiStatus) => {
  const engStatus = statusMapping[thaiStatus] || "Other";
  return engStatus;
};
